### PR TITLE
Set Slope.ECS.Examples module to open

### LINKED ISSUE #14: java.lang.IllegalAccessException when running example guessing game
**Version**:
both 0.0.8 and 0.0.9.

**Issue**: 
When running the example guessing game, the following will occur:

```
> Task :GuessingGameExample.main()
Welcome to Guessing Game!
Your goal is to find the secret entity with the special number.

Would you like to play a round? (y/N): 
Alllllright, let's get into it!

Exception in thread "main" java.lang.IllegalStateException: java.lang.IllegalAccessException: class io.github.lucasstarsz.slopeecs.system.ECSSystemManager (in module slope.ecs) cannot access class examples.guessinggame.systems.NumberSystem (in module Slope.ECS.examples) because module Slope.ECS.examples does not export examples.guessinggame.systems to module slope.ecs
	at slope.ecs/io.github.lucasstarsz.slopeecs.system.ECSSystemManager.registerSystem(ECSSystemManager.java:81)
	at slope.ecs/io.github.lucasstarsz.slopeecs.World.registerSystem(World.java:183)
	at slope.ecs/io.github.lucasstarsz.slopeecs.system.ECSSystemBuilder.construct(ECSSystemBuilder.java:96)
	at slope.ecs/io.github.lucasstarsz.slopeecs.system.ECSSystemBuilder.<init>(ECSSystemBuilder.java:91)
	at slope.ecs/io.github.lucasstarsz.slopeecs.system.ECSSystemBuilder.<init>(ECSSystemBuilder.java:71)
	at Slope.ECS.examples/examples.guessinggame.game.GuessingGame.reset(GuessingGame.java:34)
	at Slope.ECS.examples/examples.guessinggame.GuessingGameExample.main(GuessingGameExample.java:23)
Caused by: java.lang.IllegalAccessException: class io.github.lucasstarsz.slopeecs.system.ECSSystemManager (in module slope.ecs) cannot access class examples.guessinggame.systems.NumberSystem (in module Slope.ECS.examples) because module Slope.ECS.examples does not export examples.guessinggame.systems to module slope.ecs
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:385)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:693)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:490)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
Caused by: java.lang.IllegalAccessException: class io.github.lucasstarsz.slopeecs.system.ECSSystemManager (in module slope.ecs) cannot access class examples.guessinggame.systems.NumberSystem (in module Slope.ECS.examples) because module Slope.ECS.examples does not export examples.guessinggame.systems to module slope.ecs

	at slope.ecs/io.github.lucasstarsz.slopeecs.system.ECSSystemManager.registerSystem(ECSSystemManager.java:74)
	... 6 more

> Task :GuessingGameExample.main() FAILED

Execution failed for task ':GuessingGameExample.main()'.
> Process 'command 'C:/Program Files/AdoptOpenJDK/jdk-15.0.2.7-hotspot/bin/java.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

This is because the module `Slope.ECS.examples` does not export to `slope.ecs` , as given in the examples.guessinggame.module-info.java file. 

**Fix**: 
This can simply fixed by setting the `Slope.ECS.examples` module to open. I'll create a PR for this.

### PR DESCRIPTION
**Pull request by nicvst**
Fixes #14

### CODE REVIEW

**Comment by lucasstarsz** [comment]
Thanks for pointing that out -- I completely forgot that modules need to access others.

However, I'm not a fan of the way you achieved [the fix](https://github.com/lucasstarsz/Slope-ECS/pull/15/commits/abb91167aa124887004e03812b3cbf2691e5fcb1#).

image
An open module certainly works fine, but it then opens up _all_ the parts of the example to the ECS. This is _fine_, but isn't really necessary.
With Java modules, the `open` keyword (as you already know) allows other modules/classes full reflective access to the section(s) specified as `open`. Instead of opening up the entire module for reflective access, I would much rather just open up what's necessary. I did some experimenting, and opening up just the `examples.guessinggame.systems` package to the `slope.ecs` module solves the problem:
```java
module Slope.ECS.examples {
    requires slope.ecs;
    opens examples.guessinggame.systems to slope.ecs;
}
```
(For more information on opening packages rather than classes, I really like [this StackOverflow answer](https://stackoverflow.com/a/46482376).)

I've no other complaints. Thanks again for noticing this; I will look into reconfiguring how the classpaths get set in my Gradle scripts so that issues like this show up properly as well.

**Comment by nicvst** [comment]
My worry lies with the Guessing Game as example project. Opening up modules on a per-package basis leaves users to export packages until their code compiles; is it clear which packages require opening up in a user project?

I'll update the PR.

**Comment by lucasstarsz** [comment]
That is a very good point, to be honest. One I'd little considered before making that comment up there! Well, I suppose it'd be one or the other -- if we go along with opening specific packages up then it'd need to be specified in the ruleset for making examples... once that exists 😅 

To be very honest with you, either or works at the point. Whatever you do decide to do, I'll commit it and make note of it in a few hours. Just make sure you're sure of it.

**Comment by nicvst** [comment]
I've committed a change that replaces the example module configuration to your suggestion. Providing both options as suggestions and using the more restrictive approach ourselves would probably be the best course of action.

**Comment by lucasstarsz** [comment]
I agree, that should suffice. If anything comes up about this in the future, I'll refer back to this. Thanks.

**Pull request merged**
